name: ToSpeak
description: An App for iOS & Android text-to-speech.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  clipboard: ^0.1.3
  get: ^4.6.5
  get_storage:
  text_to_speech: ^0.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "images/logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "images/white.png" #android
  adaptive_icon_foreground: "images/logo.png" #android
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - images/bot.png
    - images/empty.png
    - images/flutter.png
    - images/logo.png
    - images/flaticon.png
    - images/text-to-speech.png
    - images/getx.png