name: ToSpeak
description: An App for iOS & Android text-to-speech.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  clipboard: ^0.1.3
  get: ^4.6.5
  get_storage:
  text_to_speech: ^0.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  image_path: "images/logo_ios.png" #path per iOS (normale)
  image_path_android: "images/logo_android.png" #path per Android (zoomed out)
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: "images/white.png" 
  adaptive_icon_foreground: "images/logo_android.png" # la stessa di quella definita prima
  # gli ultimi due vanno messi per rendere l'icona android adattiva
  
  
flutter:
  uses-material-design: true
  assets:
    - images/bot.png
    - images/empty.png
    - images/flutter.png
    - images/flaticon.png
    - images/text-to-speech.png
    - images/getx.png