name: TalkyBot
description: An App for iOS & Android text-to-speech and speech-to-text.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  clipboard: ^0.1.3
  get: ^4.6.5
  get_storage:
  text_to_speech: ^0.2.3
  speech_to_text: ^6.1.1
  open_apps_settings: ^0.0.4
  focus_detector_v2: ^3.0.0+2
  lottie: ^2.3.2
  internet_connection_checker: ^1.0.0+1
  flutter:
    sdk: flutter
  


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  

flutter_launcher_icons:
  image_path: "images/logo_ios.png" #path per iOS (normale)
  image_path_android: "images/logo_android.png" #path per Android (zoomed out)
  android: true
  ios: true
  remove_alpha_ios: true
  # gli ultimi due vanno messi per rendere l'icona android adattiva
  adaptive_icon_background: "images/white.png" 
  adaptive_icon_foreground: "images/logo_android.png"
  
  
flutter:
  uses-material-design: true
  assets:
    - animated/empty.json
    - animated/no_internet.json
    - animated/bot_animation.json
    - animated/ear.gif
    - animated/lottie_ok.json
    - images/bot.png
    - images/flutter.png
    - images/flaticon.png
    - images/text-to-speech.png
    - images/getx.png
    - images/cancel.png
    - images/ok.png
    - images/bad_bot.png
    - images/stt.png
    - images/gesture_detector.png